# NOTES:
#  This a custom docker-compose.override.yml for development purposes
#  For using docker-compose in a production environment, rename this file and create
#  - docker-compose.dev.override.yml
#  - docker-compose.prod.override.yml

version: '3.5'

services:
  db:
    image: postgis/postgis
    env_file: docker/env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file: docker/env
    command: ["./docker/wait-for-db.sh", "db", "./manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
